Question 2: Convolution Operations with Different Parameters
Task: Implement Convolution with Different Stride and Padding


In [7]:
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D, AveragePooling2D
import matplotlib.pyplot as plt

# Task 1: Edge Detection using Sobel Filter

def edge_detection(image_path):
    # Load image in grayscale
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    # Check if image is loaded successfully
    if image is None:
        print(f"Error: Unable to load image at {image_path}")
        return

    # Apply Sobel filter in x and y direction
    sobel_x = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=3)

    # Display images
    plt.figure(figsize=(12, 4))
    plt.subplot(1, 3, 1)
    plt.imshow(image, cmap='gray')
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(sobel_x, cmap='gray')
    plt.title("Sobel X")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(sobel_y, cmap='gray')
    plt.title("Sobel Y")
    plt.axis("off")

    plt.show()

# Task 2: Max Pooling and Average Pooling

def pooling_operations():
    # Create a random 4x4 matrix
    input_matrix = np.random.randint(0, 10, (1, 4, 4, 1)).astype(np.float32)

    # Apply 2x2 Max Pooling
    max_pooling = MaxPooling2D(pool_size=(2, 2))(input_matrix)

    # Apply 2x2 Average Pooling
    avg_pooling = AveragePooling2D(pool_size=(2, 2))(input_matrix)

    # Print results
    print("Original Matrix:")
    print(input_matrix[0, :, :, 0])
    print("\nMax Pooled Matrix:")
    print(max_pooling.numpy()[0, :, :, 0])
    print("\nAverage Pooled Matrix:")
    print(avg_pooling.numpy()[0, :, :, 0])

# Example usage
# Provide a valid path to an image for edge detection
edge_detection("path_to_image.jpg")

# Perform pooling operations
pooling_operations()


Error: Unable to load image at path_to_image.jpg
Original Matrix:
[[0. 5. 4. 1.]
 [8. 9. 1. 9.]
 [7. 6. 2. 4.]
 [8. 5. 0. 0.]]

Max Pooled Matrix:
[[9. 9.]
 [8. 4.]]

Average Pooled Matrix:
[[5.5  3.75]
 [6.5  1.5 ]]


Question 3: CNN Feature Extraction with Filters and Pooling
Task 1: Implement Edge Detection Using Convolution


In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Sequential

# Define the 5x5 input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]], dtype=np.float32)

# Reshape input to match Conv2D input format: (batch_size, height, width, channels)
input_matrix = input_matrix.reshape((1, 5, 5, 1))

# Define the 3x3 kernel
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]], dtype=np.float32)

# Reshape kernel to match Conv2D kernel format
kernel = kernel.reshape((3, 3, 1, 1))

# Function to perform convolution with given stride and padding
def perform_convolution(input_data, kernel, stride, padding):
    model = Sequential([
        Conv2D(filters=1, kernel_size=(3, 3), strides=stride, padding=padding, use_bias=False)
    ])

    # Build the model before setting weights
    model.build(input_data.shape)

    # Set the kernel weights manually
    model.layers[0].set_weights([kernel])

    output = model.predict(input_data)
    return output[0, :, :, 0]  # Remove batch and channel dimensions

# Perform convolution with different settings
results = {
    "Stride=1, Padding='VALID'": perform_convolution(input_matrix, kernel, stride=1, padding='valid'),
    "Stride=1, Padding='SAME'": perform_convolution(input_matrix, kernel, stride=1, padding='same'),
    "Stride=2, Padding='VALID'": perform_convolution(input_matrix, kernel, stride=2, padding='valid'),
    "Stride=2, Padding='SAME'": perform_convolution(input_matrix, kernel, stride=2, padding='same')
}

# Print the output feature maps
for key, value in results.items():
    print(f"\n{key}:")
    print(value)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step

Stride=1, Padding='VALID':
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

Stride=1, Padding='SAME':
[[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]]

Stride=2, Padding='VALID':
[[-6. -6.]
 [-6. -6.]]

Stride=2, Padding='SAME':
[[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]]


Question 4: Implementing and Comparing CNN Architectures Task 1: Implement AlexNet Architecture

In [11]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define the AlexNet model
def create_alexnet():
    model = models.Sequential()

    # First Conv2D Layer
    model.add(layers.Conv2D(96, (11, 11), strides=4, activation='relu', input_shape=(224, 224, 3)))

    # MaxPooling Layer
    model.add(layers.MaxPooling2D(pool_size=(3, 3), strides=2))

    # Second Conv2D Layer
    model.add(layers.Conv2D(256, (5, 5), activation='relu'))

    # MaxPooling Layer
    model.add(layers.MaxPooling2D(pool_size=(3, 3), strides=2))

    # Third Conv2D Layer
    model.add(layers.Conv2D(384, (3, 3), activation='relu'))

    # Fourth Conv2D Layer
    model.add(layers.Conv2D(384, (3, 3), activation='relu'))

    # Fifth Conv2D Layer
    model.add(layers.Conv2D(256, (3, 3), activation='relu'))

    # MaxPooling Layer
    model.add(layers.MaxPooling2D(pool_size=(3, 3), strides=2))

    # Flatten Layer
    model.add(layers.Flatten())

    # Fully Connected Layer 1
    model.add(layers.Dense(4096, activation='relu'))

    # Dropout Layer
    model.add(layers.Dropout(0.5))

    # Fully Connected Layer 2
    model.add(layers.Dense(4096, activation='relu'))

    # Dropout Layer
    model.add(layers.Dropout(0.5))

    # Output Layer
    model.add(layers.Dense(10, activation='softmax'))

    # Print the model summary
    model.summary()
    return model

# Create the AlexNet model
alexnet_model = create_alexnet()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_7 (Conv2D)                    │ (None, 54, 54, 96)          │          34,944 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 26, 26, 96)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 22, 22, 256)         │         614,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 10, 10, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 8, 8, 384)           │         885,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_10 (Conv2D)                   │ (None, 6, 6, 384)           │       1,327,488 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_11 (Conv2D)                   │ (None, 4, 4, 256)           │         884,992 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 1, 1, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 4096)                │       1,052,672 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 4096)                │      16,781,312 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │          40,970 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,622,154 (82.48 MB)

 Trainable params: 21,622,154 (82.48 MB)

 Non-trainable params: 0 (0.00 B)

Task 2: Implement a Residual Block and ResNet


In [12]:
# Residual Block definition
def residual_block(input_tensor, filters):
    # First Conv2D Layer
    x = layers.Conv2D(filters, (3, 3), activation='relu', padding='same')(input_tensor)
    # Second Conv2D Layer
    x = layers.Conv2D(filters, (3, 3), activation=None, padding='same')(x)

    # Skip connection (adding input tensor to the output of the second Conv2D)
    x = layers.add([x, input_tensor])

    # ReLU activation after the skip connection
    x = layers.ReLU()(x)

    return x

# Define the ResNet model
def create_resnet():
    input_tensor = layers.Input(shape=(224, 224, 3))

    # Initial Conv2D Layer
    x = layers.Conv2D(64, (7, 7), strides=2, activation='relu', padding='same')(input_tensor)

    # Apply two residual blocks
    x = residual_block(x, 64)
    x = residual_block(x, 64)

    # Flatten Layer
    x = layers.Flatten()(x)

    # Dense Layer
    x = layers.Dense(128, activation='relu')(x)

    # Output Layer
    x = layers.Dense(10, activation='softmax')(x)

    # Create the model
    model = models.Model(inputs=input_tensor, outputs=x)

    # Print the model summary
    model.summary()
    return model

# Create the ResNet-like model
resnet_model = create_resnet()


Model: "functional_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_5             │ (None, 224, 224, 3)    │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_12 (Conv2D)        │ (None, 112, 112, 64)   │          9,472 │ input_layer_5[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_13 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_12[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_14 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_13[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add (Add)                 │ (None, 112, 112, 64)   │              0 │ conv2d_14[0][0],       │
│                           │                        │                │ conv2d_12[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ re_lu (ReLU)              │ (None, 112, 112, 64)   │              0 │ add[0][0]              │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_15 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ re_lu[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_16 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_15[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add_1 (Add)               │ (None, 112, 112, 64)   │              0 │ conv2d_16[0][0],       │
│                           │                        │                │ re_lu[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ re_lu_1 (ReLU)            │ (None, 112, 112, 64)   │              0 │ add_1[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ flatten_1 (Flatten)       │ (None, 802816)         │              0 │ re_lu_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 128)            │    102,760,576 │ flatten_1[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_4 (Dense)           │ (None, 10)             │          1,290 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 102,919,050 (392.61 MB)

 Trainable params: 102,919,050 (392.61 MB)

 Non-trainable params: 0 (0.00 B)